# https://github.com/golangci/golangci-lint/issues/456#issuecomment-617470264
issues:
  exclude-use-default: false
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
    # golint: False positive when tests are defined in package 'test'
    - func name will be used as test\.Test.* by other packages, and that stutters; consider calling this
    # gosec: Duplicated errcheck checks
    - G104
    # gosec: Too many issues in popular repos
    - (Expect directory permissions to be 0750 or less|Expect file permissions to be 0600 or less)
    # gosec: False positive is triggered by 'src, err := ioutil.ReadFile(filename)'
    - Potential file inclusion via variable

linters:
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - durationcheck
    - errname
    - errorlint
    - exportloopref
    - forcetypeassert
    - gocognit
    - gocritic
    - goerr113
    - gofmt
    - goprintffuncname
    - gosec
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - stylecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - varnamelen
    - wrapcheck
    - wsl
  disable:
    # generics
    - rowserrcheck
    - sqlclosecheck
    - wastedassign

linters-settings:
  gocognit:
    min-complexity: 15
  nakedret:
    max-func-lines: 0
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-explanation: true
    require-specific: true
  unused:
    go: 1.19
  varnamelen:
    check-return: true
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-decls:
      - is *is.I
      - t testing.T
      - t NormalizedDuration
      - v Vector
      - ok bool
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - .Err()
    ignorePackageGlobs:
      # add entry for current module here
      - golang.org/x/sync/errgroup*
      - github.com/hashicorp/go-multierror*
      - github.com/magefile/mage*
